name: Run Python API

on:
  push:
    branches:
      - main

jobs:
  run-api:
    runs-on: ubuntu-latest
    
    container:
      image: python:3.12
    
    steps:
        
    - name: Install dependencies as part of the post build actions
      run: pip install neuro-connector-api
    
    
