name: Run Python API

on:
  push:
    branches:
      - main

jobs:
  run-api:
    runs-on: ubuntu-latest
    
    container:
      image: python:3.12
    
    steps:
        
    - name: Install dependencies as part of the post build actions
      run: pip install neuro-connector-api

    - name: Run NeuroConnector.py to push the test results to neuro
      run: python3 -m neuro-connector-api.NeuroConnector --func sendTestNGResults --org 123123123 --path testng.json --jobname jobNameExample --url https://app.myneuro.ai
    
    
